[package]
name = "pubsub_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
atomic = "0.6.1"
bytemuck = "1.24.0"
multimap = "0.10.1"
num = "0.4.3"
rand = "0.9.2"
#tokio = "1.48.0"
tokio = { version = "1.0", features = ["full"] }
